<img src="https://github.com/ProgramSKAN/Sample-Data-For-Machine-Learning/blob/master/ann1.PNG?raw=true">
<img src="https://github.com/ProgramSKAN/Sample-Data-For-Machine-Learning/blob/master/ann2.PNG?raw=true">
<img src="https://github.com/ProgramSKAN/Sample-Data-For-Machine-Learning/blob/master/ann3.PNG?raw=true">
<img src="https://github.com/ProgramSKAN/Sample-Data-For-Machine-Learning/blob/master/ann4.PNG?raw=true">
<img src="https://github.com/ProgramSKAN/Sample-Data-For-Machine-Learning/blob/master/ann5.PNG?raw=true">
<img src="https://github.com/ProgramSKAN/Sample-Data-For-Machine-Learning/blob/master/ann6.PNG?raw=true">
<img src="https://github.com/ProgramSKAN/Sample-Data-For-Machine-Learning/blob/master/ann7.PNG?raw=true">
<img src="https://github.com/ProgramSKAN/Sample-Data-For-Machine-Learning/blob/master/ann8.PNG?raw=true">
<img src="https://github.com/ProgramSKAN/Sample-Data-For-Machine-Learning/blob/master/ann9.PNG?raw=true">
<img src="https://github.com/ProgramSKAN/Sample-Data-For-Machine-Learning/blob/master/ann10.PNG?raw=true"><img src="https://github.com/ProgramSKAN/Sample-Data-For-Machine-Learning/blob/master/ann1.PNG?raw=true">
<img src="https://github.com/ProgramSKAN/Sample-Data-For-Machine-Learning/blob/master/ann11.PNG?raw=true">
<img src="https://github.com/ProgramSKAN/Sample-Data-For-Machine-Learning/blob/master/ann12.PNG?raw=true">
<img src="https://github.com/ProgramSKAN/Sample-Data-For-Machine-Learning/blob/master/ann13.PNG?raw=true">
<img src="https://github.com/ProgramSKAN/Sample-Data-For-Machine-Learning/blob/master/ann14.PNG?raw=true">
<img src="https://github.com/ProgramSKAN/Sample-Data-For-Machine-Learning/blob/master/ann15.PNG?raw=true">
<img src="https://github.com/ProgramSKAN/Sample-Data-For-Machine-Learning/blob/master/ann16.PNG?raw=true">
<img src="https://github.com/ProgramSKAN/Sample-Data-For-Machine-Learning/blob/master/ann17.PNG?raw=true">
<img src="https://github.com/ProgramSKAN/Sample-Data-For-Machine-Learning/blob/master/ann18.PNG?raw=true">
<img src="https://github.com/ProgramSKAN/Sample-Data-For-Machine-Learning/blob/master/ann19.PNG?raw=true">
<img src="https://github.com/ProgramSKAN/Sample-Data-For-Machine-Learning/blob/master/ann20.PNG?raw=true">
<img src="https://github.com/ProgramSKAN/Sample-Data-For-Machine-Learning/blob/master/ann21.PNG?raw=true">
<img src="https://github.com/ProgramSKAN/Sample-Data-For-Machine-Learning/blob/master/ann22.PNG?raw=true">
<img src="https://github.com/ProgramSKAN/Sample-Data-For-Machine-Learning/blob/master/ann23.PNG?raw=true">
<img src="https://github.com/ProgramSKAN/Sample-Data-For-Machine-Learning/blob/master/ann24.PNG?raw=true">
<img src="https://github.com/ProgramSKAN/Sample-Data-For-Machine-Learning/blob/master/ann25.PNG?raw=true">
<img src="https://github.com/ProgramSKAN/Sample-Data-For-Machine-Learning/blob/master/ann26.PNG?raw=true">
<img src="https://github.com/ProgramSKAN/Sample-Data-For-Machine-Learning/blob/master/ann27.PNG?raw=true">
<img src="https://github.com/ProgramSKAN/Sample-Data-For-Machine-Learning/blob/master/ann28.PNG?raw=true">
<img src="https://github.com/ProgramSKAN/Sample-Data-For-Machine-Learning/blob/master/ann29.PNG?raw=true">
<img src="https://github.com/ProgramSKAN/Sample-Data-For-Machine-Learning/blob/master/ann30.PNG?raw=true">
<img src="https://github.com/ProgramSKAN/Sample-Data-For-Machine-Learning/blob/master/ann31.PNG?raw=true">
<img src="https://github.com/ProgramSKAN/Sample-Data-For-Machine-Learning/blob/master/ann32.PNG?raw=true">
<img src="https://github.com/ProgramSKAN/Sample-Data-For-Machine-Learning/blob/master/ann33.PNG?raw=true">
<img src="https://github.com/ProgramSKAN/Sample-Data-For-Machine-Learning/blob/master/ann34.PNG?raw=true">
<img src="https://github.com/ProgramSKAN/Sample-Data-For-Machine-Learning/blob/master/ann35.PNG?raw=true">
<img src="https://github.com/ProgramSKAN/Sample-Data-For-Machine-Learning/blob/master/ann36.PNG?raw=true">
<img src="https://github.com/ProgramSKAN/Sample-Data-For-Machine-Learning/blob/master/ann37.PNG?raw=true">
<img src="https://github.com/ProgramSKAN/Sample-Data-For-Machine-Learning/blob/master/ann38.PNG?raw=true">
<img src="https://github.com/ProgramSKAN/Sample-Data-For-Machine-Learning/blob/master/ann39.PNG?raw=true">
we adjust the weight so that Cost function is minimum.so gradient descent is easy to get the best weight instead of brutforcing all combinations which takes life time.But Gradiesnt disent method needs cost fuction to be convex.but is the cost function is not half the square of the distance, in Higher dimension,the cont fuction is irregular.so in that case gadient discent falsly get the local minimum than global minimum cost fuction.so, in that case use stocastic gradient discent which doesnt require cost fuction to be convex.


it works becasue in gradient discent(batch gradient discent) we adjust the weights after whole batch of samples pass throgh the network but in stochastic gradient discent it adjusts the weights for every record pass through the network.

Grdient descent:
1.batch
2.miini batch
3.stochastic


when all the sample records are pass throgh the neural network, that makes the epoch.

ANN can be used for both Regression and Classification.
below example is for classification .
for regresion check https://www.udemy.com/course/linear-regression-with-artificial-neural-network/

# Artificial Neural Network

### Importing the libraries

In [34]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [35]:
tf.__version__

'2.2.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [36]:
#given bank data of RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited. predict why people exiting the bank?
dataset = pd.read_csv('https://raw.githubusercontent.com/ProgramSKAN/Sample-Data-For-Machine-Learning/master/Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [37]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [38]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [39]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [40]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [41]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [42]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [43]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling
must for Deep learning

In [44]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [45]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [46]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu')) #relu>rectifier activation function

### Adding the second hidden layer

In [47]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [48]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid')) #sigmoid because it gives the probability.ie:it not only says whether customer exited/not but it also gives probability

## Part 3 - Training the ANN

### Compiling the ANN

In [49]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy']) 
#adam>stochastic gradient descent ,loss function is a way to predict difference between prediction and real result
#loss = 'binary_crossentropy > for binary classification
#loss = 'categorical_crossentropy > for non binary classification.ex:3 different classifications

### Training the ANN on the Training set

In [50]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100) 
#the batch size parameter gives the number of predictions you want to have in the batch to be compared to that same number of real results.

Epoch 1/100
250/250 [==============================] - 0s 1ms/step - loss: 0.5135 - accuracy: 0.7962
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4591 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4393 - accuracy: 0.7981
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4300 - accuracy: 0.8083
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4250 - accuracy: 0.8138
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4203 - accuracy: 0.8191
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4157 - accuracy: 0.8217
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4104 - accuracy: 0.8244
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4051 - accuracy: 0.8274
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4006 - accura

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer ?

**Solution**

In [51]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [52]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [53]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1503   92]
 [ 197  208]]


0.8555

https://www.superdatascience.com/blogs/the-ultimate-guide-to-artificial-neural-networks-ann

https://www.slideshare.net/KirillEremenko/deep-learning-az-artificial-neural-networks-ann-module-1